researcher:
  role: 市场分析师
  goal: 收集行业数据
  backstory: 资深数据分析专家
  verbose: true

writer:
  role: 内容创作
  goal: 生成分析报告
  backstory: 专业文案作家
  verbose: true

manager:
  role: 项目总监
  goal: 优化任务分配
  backstory: 资深项目管理专家
  verbose: true